# NuKeeper Pipeline
# This should
# - Run every Sunday morning
# - Run NuKeeper on the repository to automatically upgrade NuGet packages
schedules:
- cron: "0 0 * * 0"
  displayName: Weekly on Sunday Morning
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-18.04'

variables:
  githubRepositoryUrl: 'https://github.com/CapitalOnTap/marqeta-csharp-core-abstractions'

steps:
- task: NuKeeper@0
  inputs:
    arguments: 'repo $(githubRepositoryUrl)'
    version: '0.*'