# NuKeeper Pipeline
# This should
# - Run every Sunday morning
# - Run NuKeeper on the repository to automatically upgrade NuGet packages
schedules:
- cron: "0 0 * * 0"
  displayName: Weekly on Sunday Morning
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-18.04'

variables:
  githubRepositoryUrl: 'https://github.com/CapitalOnTap/marqeta-csharp-core-abstractions'

steps:
- task: PowerShell@2
  displayName: 'Install NuKeeper'
  inputs:
    targetType: 'inline'
    script: |
      dotnet tool install nukeeper --global

- task: PowerShell@2
  displayName: 'Run NuKeeper for repository ''$(githubRepositoryUrl)'''
  inputs:
    targetType: 'inline'
    script: |
      nukeeper repo $(githubRepositoryUrl)