trigger:
  branches:
    include:
    - master
    - releases/*
    - azure-pipelines-testing/*
    
pr:
  branches:
    include:
    - master
    - releases/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  gitVersionVersion: '4.0.0'

steps:
# - task: GitVersion@4
#   displayName: 'GitVersion'
#   inputs:
#     updateAssemblyInfo: true
- task: NuGetCommand@2
  inputs:
    command: custom
    arguments: install GitVersion.CommandLine -Version $(gitVersionVersion) -OutputDirectory $(Build.BinariesDirectory)/tools -ExcludeVersion
  displayName: 'Install GitVersion $(gitVersionVersion)'
- script: mono $(Build.BinariesDirectory)/tools/GitVersion.CommandLine/tools/GitVersion.exe /output build
  displayName: 'Run GitVersion'
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- script: dotnet test --configuration $(buildConfiguration)
  displayName: 'dotnet test $(buildConfiguration)'
